### ISSUE TITLE
Camera Width, logfile has for long time showed 1 single "warning" , now it's "followed but a bunch of, with below "error-handling-Traceback"

### ISSUE THREAD

**Issue by boheme61** [Danielhiversen/home_assistant_tibber_custom#29]
2022-04-07 21:13:07 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 724, in get
return await self.handle(request, camera)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 742, in handle
image = await _async_get_image(
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 163, in _async_get_image
if image_bytes := await camera.async_camera_image(
TypeError: async_camera_image() got an unexpected keyword argument 'width'
2022-04-07 21:13:58 ERROR (MainThread) [aiohttp.server] Error handling request

**Comment by boheme61** [comment]
async_camera_image() got an unexpected keyword argument 'width' 
... guess it's width for the "Plotter-Pic" , or ?

**Comment by boheme61** [comment]
Adding another "snippet" of resent log-entries:

File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 163, in _async_get_image
if image_bytes := await camera.async_camera_image(
TypeError: async_camera_image() got an unexpected keyword argument 'width'

2022-04-07 22:46:12 ERROR (MainThread) [frontend.js.latest.202204050] :0:0 ResizeObserver loop completed with undelivered notifications.
2022-04-07 22:46:15 WARNING (SyncWorker_5) [homeassistant.helpers.frame] Detected code that accesses the database without the database executor; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job() for faster database operations. Please report this issue.

Stack (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
self._bootstrap_inner()
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 83, in _worker
work_item.run()
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)

And i don't see any Picture / Graph, seems like the Card is "broken" ... i'll try to reinstall the Integration ... and report back

PS: these logs was from after i Updated to 2022.4

**Comment by boheme61** [comment]
Logger: aiohttp.server
Source: components/camera/__init__.py:163
First occurred: 09:48:53 (12 occurrences)
Last logged: 10:00:47
Error handling request

Traceback (most recent call last):

**Comment by boheme61** [comment]
> I have exactly the same issue here after upgrading to 2022.4.1 from 2022.3.8.
Apparently latest "update" 2022.4 change something ... so

Go to your card and change "Camera View" from Auto to Live ... at-least you get the picture right(back again) ... though still the exception still occurs:
" TypeError: async_camera_image() got an unexpected keyword argument 'width'

**Comment by boheme61** [comment]
> ill wait until tomorrows "price updates" , to see whether the "old" exception occurs, then i close this

On second though, i Rebooted Host, picture changed to 48 hours view ... no exeptions

Closing this, as integration works as expected.

**Comment by boheme61** [comment]
I haven't had any problems after i "changed" to "Live", and haven't bother to find out the difference, it works, and no exceptions since i closed it, not even the usual (unexpected keyword argument 'width') .
Have you installed latest HA updates core-2022.4.2 And supervisor-2022.04.0 ?

PS: I did also "re-downloaded" the integration in HACS, try that to, or delete it and install it again

... In regards to cast to Google devices, have you confirmed that it's due to this integration ? , as  i don't do this, or are aware that it suppose to work, i haven't any ideas.

If you don't get rid of the "Warning -message" after above "Tips" ,  you can open a new "Issue" , with relevant logs and your system-status etc.
